# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "metronic"
client_id = "f5b89da9a0c100733ec7bf290a0147d1"
application_url = "https://republicans-grad-atlantic-leo.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://republicans-grad-atlantic-leo.trycloudflare.com/auth/callback",
  "https://republicans-grad-atlantic-leo.trycloudflare.com/auth/shopify/callback",
  "https://republicans-grad-atlantic-leo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1b549435.myshopify.com"
